In [1]:
import numpy as np
import pandas as pd

import scanpy as sc
import scvelo as scv

import matplotlib.pyplot as plt
import seaborn as sns

import myutils

import random
import os

myutils.set_figure_params()
sc.settings.verbosity = 3

In [4]:
adata = sc.read_h5ad("../1_preprocess_integration/1.3.final_all_for_open_access.h5ad")
adata

AnnData object with n_obs × n_vars = 166418 × 25998
    obs: 'cell_id', 'sample', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'n_counts', 'condition', 'leiden', 'CellType', 'condition_final'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'CellType_colors', 'batch_colors', 'condition_colors', 'hvg', 'leiden', 'leiden_colors', 'log1p', 'neighbors', 'pca', 'sample_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [5]:
KC_meta = sc.read_h5ad("../2_keratinocyte/2.1.keratinocyte_final.h5ad").obs
KC_meta.head(5)

,cell_id,sample,n_genes,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,n_counts,condition,leiden,CellType,condition_final,leiden1.0,leiden0.5,CellType2
HS1_0_CELL520_N2,HS1_0_CELL520_N2,HS1,3555,3555,17932.0,634.0,3.535579,17932.0,Scar/keloid,0,Keratinocyte,Hypertrophic Scar,1,0,Spi-1
HS1_0_CELL7176_N1,HS1_0_CELL7176_N1,HS1,1277,1277,6158.0,235.0,3.816174,6158.0,Scar/keloid,0,Keratinocyte,Hypertrophic Scar,3,1,Spi-EMT
HS1_0_CELL2387_N2,HS1_0_CELL2387_N2,HS1,2055,2055,10163.0,388.0,3.817770,10163.0,Scar/keloid,0,Keratinocyte,Hypertrophic Scar,1,0,Spi-1
HS1_0_CELL676_N2,HS1_0_CELL676_N2,HS1,3194,3194,18461.0,355.0,1.922973,18461.0,Scar/keloid,0,Keratinocyte,Hypertrophic Scar,9,6,Spi-2
HS1_0_CELL3719_N1,HS1_0_CELL3719_N1,HS1,2479,2479,12169.0,629.0,5.168871,12169.0,Scar/keloid,4,Keratinocyte,Hypertrophic Scar,0,2,Bas

In [6]:
FB_meta = sc.read_h5ad("../3_fibroblasts/3.1.fibroblast_final.h5ad").obs
FB_meta.head(5)

,cell_id,sample,n_genes,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,n_counts,condition,leiden,CellType,condition_final,leiden1.0,CellType2
HS1_0_CELL5242_N1,HS1_0_CELL5242_N1,HS1,1162,1162,3954.0,147.0,3.717754,3954.0,Scar/keloid,2,Fibroblast,Hypertrophic Scar,0,Fibroblast (non-myo)
HS1_0_CELL9007_N1,HS1_0_CELL9007_N1,HS1,3770,3770,18157.0,436.0,2.401278,18157.0,Scar/keloid,2,Fibroblast,Hypertrophic Scar,5,Myofibroblast
HS1_0_CELL4107_N1,HS1_0_CELL4107_N1,HS1,825,825,2153.0,65.0,3.019043,2153.0,Scar/keloid,2,Fibroblast,Hypertrophic Scar,12,Fibroblast (non-myo)
HS1_0_CELL3221_N1,HS1_0_CELL3221_N1,HS1,3462,3462,13849.0,660.0,4.765687,13849.0,Scar/keloid,2,Fibroblast,Hypertrophic Scar,4,Myofibroblast
HS1_0_CELL134_N1,HS1_0_CELL134_N1,HS1,2186,2186,7660.0,278.0,3.629243,7660.0,Scar/keloid,2,Fibroblast,Hypertrophic Scar,11,Fibroblast (non-myo)

In [7]:
tmp = adata.obs['CellType'].to_numpy()
adata.obs['CellType_cellphone'] = tmp
adata.obs.loc[KC_meta['cell_id'],"CellType_cellphone"] = KC_meta['CellType2']
adata.obs.loc[FB_meta['cell_id'],"CellType_cellphone"] = FB_meta['CellType2']
adata = adata[~adata.obs['CellType_cellphone'].isin(["Fibroblast","Keratinocyte"])]
adata.obs['CellType_cellphone'].unique()

array(['Pericyte', 'T Cell', 'Fibroblast (non-myo)', 'Myofibroblast',
       'Endothelial Cell', 'Mast Cell', 'Neuron', 'Spi-1', 'Spi-EMT',
       'Spi-2', 'Bas', 'Myeloid Cell', 'Bas-pro', 'Sweat Gland Cell',
       'Granu', 'Melanocyte', 'Bas-EMT'], dtype=object)

In [9]:
os.mkdir("5.1.CellPhoneDB")

In [10]:
metadata = pd.DataFrame(adata.obs_names)
metadata['cell_type'] = adata.obs['CellType_cellphone'].tolist()
metadata.columns = ['sample_barcode',"cell_type"]
metadata.to_csv("5.1.CellPhoneDB/metadata.tsv",sep="\t",index=None)
metadata

                sample_barcode             cell_type
0             HS1_0_CELL773_N2              Pericyte
1            HS1_0_CELL2512_N1                T Cell
2            HS1_0_CELL5242_N1  Fibroblast (non-myo)
3            HS1_0_CELL9007_N1         Myofibroblast
4            HS1_0_CELL4359_N1      Endothelial Cell
...                        ...                   ...
159646   Normal4_1_CELL5174_N1      Sweat Gland Cell
159647  Normal4_1_CELL10815_N1                   Bas
159648   Normal4_1_CELL3801_N1               Spi-EMT
159649   Normal4_1_CELL5675_N1                   Bas
159650   Normal4_1_CELL6177_N1          Myeloid Cell

[159651 rows x 2 columns]

In [12]:
adata.write_h5ad("5.1.CellPhoneDB/normalised_log_counts.h5ad")

In [13]:
adata.obs['condition']

HS1_0_CELL773_N2          Scar/keloid
HS1_0_CELL2512_N1         Scar/keloid
HS1_0_CELL5242_N1         Scar/keloid
HS1_0_CELL9007_N1         Scar/keloid
HS1_0_CELL4359_N1         Scar/keloid
                             ...
Normal4_1_CELL5174_N1              NS
Normal4_1_CELL10815_N1             NS
Normal4_1_CELL3801_N1              NS
Normal4_1_CELL5675_N1              NS
Normal4_1_CELL6177_N1              NS
Name: condition, Length: 159651, dtype: category
Categories (2, object): ['NS', 'Scar/keloid']

In [14]:
tmp = [i[0]+"_"+i[1] for i in zip(adata.obs['CellType_cellphone'],adata.obs['condition'])]
adata.obs['CellType_cellphone2'] = tmp
adata.obs['CellType_cellphone2'].unique()

array(['Pericyte_Scar/keloid', 'T Cell_Scar/keloid',
       'Fibroblast (non-myo)_Scar/keloid', 'Myofibroblast_Scar/keloid',
       'Endothelial Cell_Scar/keloid', 'Mast Cell_Scar/keloid',
       'Neuron_Scar/keloid', 'Spi-1_Scar/keloid', 'Spi-EMT_Scar/keloid',
       'Spi-2_Scar/keloid', 'Bas_Scar/keloid', 'Myeloid Cell_Scar/keloid',
       'Bas-pro_Scar/keloid', 'Sweat Gland Cell_Scar/keloid',
       'Granu_Scar/keloid', 'Melanocyte_Scar/keloid',
       'Bas-EMT_Scar/keloid', 'Endothelial Cell_NS', 'Bas_NS', 'Granu_NS',
       'Fibroblast (non-myo)_NS', 'Pericyte_NS', 'Myeloid Cell_NS',
       'Sweat Gland Cell_NS', 'Spi-EMT_NS', 'Spi-1_NS', 'Bas-pro_NS',
       'Melanocyte_NS', 'T Cell_NS', 'Neuron_NS', 'Bas-EMT_NS',
       'Mast Cell_NS', 'Spi-2_NS', 'Myofibroblast_NS'], dtype=object)

In [17]:
metadata = pd.DataFrame(adata.obs_names)
metadata['cell_type'] = adata.obs['CellType_cellphone2'].tolist()
metadata.columns = ['sample_barcode',"cell_type"]
metadata.to_csv("5.1.CellPhoneDB/metadata_by_condition.tsv",sep="\t",index=None)
metadata

                sample_barcode                         cell_type
0             HS1_0_CELL773_N2              Pericyte_Scar/keloid
1            HS1_0_CELL2512_N1                T Cell_Scar/keloid
2            HS1_0_CELL5242_N1  Fibroblast (non-myo)_Scar/keloid
3            HS1_0_CELL9007_N1         Myofibroblast_Scar/keloid
4            HS1_0_CELL4359_N1      Endothelial Cell_Scar/keloid
...                        ...                               ...
159646   Normal4_1_CELL5174_N1               Sweat Gland Cell_NS
159647  Normal4_1_CELL10815_N1                            Bas_NS
159648   Normal4_1_CELL3801_N1                        Spi-EMT_NS
159649   Normal4_1_CELL5675_N1                            Bas_NS
159650   Normal4_1_CELL6177_N1                   Myeloid Cell_NS

[159651 rows x 2 columns]

In [18]:
adata.write_h5ad("5.1.CellPhoneDB/normalised_log_counts_by_condition.h5ad")

In [19]:
!conda list

# packages in environment at C:\Users\dell\.conda\envs\scanpy:
#
# Name                    Version                   Build  Channel
absl-py                   2.3.0                    pypi_0    pypi
adjusttext                1.3.0                    pypi_0    pypi
aiobotocore               2.5.4                    pypi_0    pypi
aiohappyeyeballs          2.6.1                    pypi_0    pypi
aiohttp                   3.12.4                   pypi_0    pypi
aioitertools              0.12.0                   pypi_0    pypi
aiosignal                 1.3.2                    pypi_0    pypi
anndata                   0.10.8                   pypi_0    pypi
anyio                     4.8.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
array-api-compat          1.10.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 3.0.0                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
async-timeout             5.0.1                    pypi_0    pypi
attrs                     25.1.0                   pypi_0    pypi
babel                     2.17.0                   pypi_0    pypi
beautifulsoup4            4.13.3                   pypi_0    pypi
blas                      1.0                         mkl    defaults
bleach                    6.2.0                    pypi_0    pypi
blosc2                    2.5.1                    pypi_0    pypi
botocore                  1.31.17                  pypi_0    pypi
bottleneck                1.4.2            py39hc99e966_0    defaults
brotli-python             1.0.9            py39h5da7b33_9    defaults
ca-certificates           2025.2.25            haa95532_0    defaults
cell2location             0.1.4                    pypi_0    pypi
cellrank                  2.0.6                    pypi_0    pypi
certifi                   2025.1.31                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
chex                      0.1.89                   pypi_0    pypi
click                     8.1.8            py39haa95532_0    defaults
cloudpickle               3.0.0            py39haa95532_0    defaults
clustercleaver            0.0.0.3                  pypi_0    pypi
colorama                  0.4.6            py39haa95532_0    defaults
colorcet                  3.1.0            py39haa95532_0    defaults
comm                      0.2.2                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dask-core                 2024.5.0         py39haa95532_0    defaults
dask-expr                 1.1.0                    pypi_0    pypi
dask-image                2024.5.3                 pypi_0    pypi
datashader                0.16.3           py39haa95532_1    defaults
debugpy                   1.8.12                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
decoupler                 1.9.0                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
distributed               2024.5.0                 pypi_0    pypi
docrep                    0.3.2                    pypi_0    pypi
et-xmlfile                2.0.0                    pypi_0    pypi
etils                     1.5.2                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.2.0                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
fastjsonschema            2.21.1                   pypi_0    pypi
fcsparser                 0.2.8                    pypi_0    pypi
filelock                  3.18.0                   pypi_0    pypi
flax                      0.8.5                    pypi_0    pypi
fonttools                 4.56.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freeglut                  3.4.0                hd77b12b_0    defaults
freetype                  2.13.3               h0620614_0    defaults
frozenlist                1.6.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
geopandas                 1.0.1                    pypi_0    pypi
get-annotations           0.1.2                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.12.1                   pypi_0    pypi
harmonypy                 0.0.10                   pypi_0    pypi
httpcore                  1.0.7                    pypi_0    pypi
httpx                     0.28.1                   pypi_0    pypi
humanize                  4.12.3                   pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2    defaults
idna                      3.10                     pypi_0    pypi
igraph                    0.11.8                   pypi_0    pypi
imageio                   2.37.0                   pypi_0    pypi
importlib-metadata        8.6.1                    pypi_0    pypi
importlib-resources       6.5.2                    pypi_0    pypi
inflect                   7.5.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320    defaults
ipykernel                 6.29.5                   pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jax                       0.4.30                   pypi_0    pypi
jaxlib                    0.4.30                   pypi_0    pypi
jaxopt                    0.8.3                    pypi_0    pypi
jedi                      0.19.2                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h827c3e9_3    defaults
json5                     0.10.0                   pypi_0    pypi
jsonpointer               3.0.0                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
jupyter-client            8.6.3                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyter-events            0.12.0                   pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.15.0                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyterlab                4.3.5                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.27.3                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.16                 h62be587_1    defaults
legacy-api-wrap           1.4.1                    pypi_0    pypi
leidenalg                 0.10.2                   pypi_0    pypi
lerc                      4.0.0                h5da7b33_0    defaults
libdeflate                1.22                 h5bf469e_0    defaults
libpng                    1.6.39               h8cc25b3_0    defaults
libtiff                   4.7.0                h404307b_0    defaults
libwebp-base              1.3.2                h3d04722_1    defaults
lightning                 2.5.1.post0              pypi_0    pypi
lightning-utilities       0.14.3                   pypi_0    pypi
llvmlite                  0.43.0           py39hf2fb9eb_1    defaults
locket                    1.0.0            py39haa95532_0    defaults
loompy                    3.0.8                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_1    defaults
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
matplotlib                3.9.4                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
matplotlib-scalebar       0.9.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mellon                    1.5.0                    pypi_0    pypi
mistune                   3.1.1                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358    defaults
mkl-service               2.4.0            py39h827c3e9_2    defaults
mkl_fft                   1.3.11           py39h827c3e9_0    defaults
mkl_random                1.2.8            py39hc64d2fc_0    defaults
ml-collections            0.1.1                    pypi_0    pypi
ml-dtypes                 0.5.1                    pypi_0    pypi
more-itertools            10.7.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
mudata                    0.2.4                    pypi_0    pypi
multidict                 6.4.4                    pypi_0    pypi
multipledispatch          1.0.0                    pypi_0    pypi
multiscale-spatial-image  1.0.1                    pypi_0    pypi
myutils                   0.1.1                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
nbclient                  0.10.2                   pypi_0    pypi
nbconvert                 7.16.6                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ndindex                   1.9.2                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
notebook                  7.3.2                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numba                     0.60.0           py39h5da7b33_1    defaults
numcodecs                 0.12.1                   pypi_0    pypi
numexpr                   2.10.2                   pypi_0    pypi
numpy                     1.26.4           py39h055cbcc_0    defaults
numpy-base                1.26.4           py39h65a83cf_0    defaults
numpy-groupies            0.11.2                   pypi_0    pypi
numpyro                   0.18.0                   pypi_0    pypi
ome-zarr                  0.10.2                   pypi_0    pypi
omnipath                  1.0.10                   pypi_0    pypi
opencv-python             4.11.0.86                pypi_0    pypi
openjpeg                  2.5.2                h9b5d1b5_1    defaults
openpyxl                  3.1.5                    pypi_0    pypi
openssl                   3.0.16               h3f729d1_0    defaults
opt-einsum                3.4.0                    pypi_0    pypi
optax                     0.2.4                    pypi_0    pypi
orbax-checkpoint          0.6.4                    pypi_0    pypi
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.2             py39haa95532_0    defaults
palantir                  1.3.6                    pypi_0    pypi
pandas                    2.2.3            py39h5da7b33_0    defaults
pandocfilters             1.5.1                    pypi_0    pypi
param                     2.2.0            py39haa95532_0    defaults
parso                     0.8.4                    pypi_0    pypi
partd                     1.4.2            py39haa95532_0    defaults
patsy                     1.0.1                    pypi_0    pypi
phenograph                1.5.7                    pypi_0    pypi
pillow                    11.1.0           py39hea0d53e_1    defaults
pims                      0.7                      pypi_0    pypi
pip                       25.0             py39haa95532_0    defaults
platformdirs              4.3.6                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
progressbar2              4.5.0                    pypi_0    pypi
prometheus-client         0.21.1                   pypi_0    pypi
prompt-toolkit            3.0.50                   pypi_0    pypi
propcache                 0.3.1                    pypi_0    pypi
protobuf                  6.31.1                   pypi_0    pypi
psutil                    6.1.1                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   20.0.0                   pypi_0    pypi
pybind11-abi              5                    hd3eb1b0_0    defaults
pycparser                 2.22                     pypi_0    pypi
pyct                      0.5.0            py39haa95532_0    defaults
pydeseq2                  0.4.12                   pypi_0    pypi
pygam                     0.9.1                    pypi_0    pypi
pygments                  2.19.1                   pypi_0    pypi
pygpcca                   1.0.4                    pypi_0    pypi
pynndescent               0.5.13                   pypi_0    pypi
pyogrio                   0.11.0                   pypi_0    pypi
pyparsing                 3.2.1                    pypi_0    pypi
pyproj                    3.6.1                    pypi_0    pypi
pyro-api                  0.1.2                    pypi_0    pypi
pyro-ppl                  1.9.1                    pypi_0    pypi
pysocks                   1.7.1            py39haa95532_0    defaults
python                    3.9.21               h8205438_1    defaults
python-dateutil           2.9.0post0       py39haa95532_2    defaults
python-json-logger        3.2.1                    pypi_0    pypi
python-tzdata             2025.2             pyhd3eb1b0_0    defaults
python-utils              3.9.1                    pypi_0    pypi
pytorch-lightning         2.5.1.post0              pypi_0    pypi
pytz                      2025.1                   pypi_0    pypi
pywin32                   308                      pypi_0    pypi
pywinpty                  2.0.15                   pypi_0    pypi
pyyaml                    6.0.2            py39h827c3e9_0    defaults
pyzmq                     26.2.1                   pypi_0    pypi
referencing               0.36.2                   pypi_0    pypi
requests                  2.32.3           py39haa95532_1    defaults
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      14.0.0                   pypi_0    pypi
rpds-py                   0.22.3                   pypi_0    pypi
s3fs                      2023.6.0                 pypi_0    pypi
scanpy                    1.10.3                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.6.1                    pypi_0    pypi
scipy                     1.13.1           py39h8640f81_1    defaults
scvelo                    0.3.3                    pypi_0    pypi
scvi-tools                1.1.6.post2              pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                75.8.0           py39haa95532_0    defaults
shapely                   2.0.7                    pypi_0    pypi
six                       1.17.0           py39haa95532_0    defaults
slicerator                1.1.0                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
spatial-image             1.1.0                    pypi_0    pypi
spatialdata               0.2.5.post0              pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0    defaults
squidpy                   1.6.1                    pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
statsmodels               0.14.4                   pypi_0    pypi
stdlib-list               0.11.0                   pypi_0    pypi
sympy                     1.14.0                   pypi_0    pypi
tables                    3.9.2                    pypi_0    pypi
tbb                       2022.0.0                 pypi_0    pypi
tblib                     3.1.0                    pypi_0    pypi
tcmlib                    1.2.0                    pypi_0    pypi
tensorstore               0.1.69                   pypi_0    pypi
terminado                 0.18.1                   pypi_0    pypi
texttable                 1.7.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
tinycss2                  1.4.0                    pypi_0    pypi
tomli                     2.2.1                    pypi_0    pypi
toolz                     1.0.0            py39haa95532_0    defaults
torch                     2.7.0                    pypi_0    pypi
torchmetrics              1.7.2                    pypi_0    pypi
tornado                   6.4.2                    pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
typeguard                 4.4.2                    pypi_0    pypi
types-python-dateutil     2.9.0.20241206           pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2025.1                   pypi_0    pypi
umap-learn                0.5.7                    pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.20                  pypi_0    pypi
validators                0.35.0                   pypi_0    pypi
vc                        14.42                haa95532_3    defaults
vs2015_runtime            14.42.34433          he0abc0d_3    defaults
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 24.11.1                  pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
wheel                     0.45.1           py39haa95532_0    defaults
win_inet_pton             1.1.0            py39haa95532_0    defaults
wrapt                     1.17.2                   pypi_0    pypi
xarray                    2024.7.0                 pypi_0    pypi
xarray-dataclasses        1.9.1                    pypi_0    pypi
xarray-datatree           0.0.15                   pypi_0    pypi
xarray-schema             0.0.3                    pypi_0    pypi
xarray-spatial            0.4.0                    pypi_0    pypi
xz                        5.6.4                h4754444_1    defaults
yaml                      0.2.5                he774522_0    defaults
yarl                      1.20.0                   pypi_0    pypi
zarr                      2.18.2                   pypi_0    pypi
zict                      3.0.0                    pypi_0    pypi
zipp                      3.21.0           py39haa95532_0    defaults
zlib                      1.2.13               h8cc25b3_1    defaults
zstd                      1.5.6                h8880b57_0    defaults